fix new gcc compile warnings about unused variables
The latest yocto has brought in a new gcc which is causing building of
this repo due to fails like this:

```
slpd-lite/sock_channel.cpp:27:23: error: value computed is not used [-Werror=unused-value]
|    27 |     buffer outBuffer(0);
|       |
```

Fix this by just using the default vector constructor with no arguments
(resulting in a empty container to start with).

Change-Id: If06dfccd2aa234956e124c11bd268198be569e6d
Signed-off-by: Andrew Geissler <geissonator@yahoo.com>